### ISSUE TITLE
Is there any way to improve the process speed?

### ISSUE THREAD

**Issue by TakiOrange** [TanBinh93/Structure-from-Motion-based-on-Dense-Optical-Flow-method#1]
Hi! Thank you for sharing the code. 

I have successfully run the sample code with the default 4 images but it almost took me 40 mins. I understand that dense optical flow is very time consuming, but since the complexity will improve greatly with more images, I wonder whether this speed is within expectation. 
If not, is there any key to improve the process speed? 

I'm using Matlab R2021a with i7-9700K processor, GeForce RTX 3070.

Besides, through the sample code, I saved the extracted HP groups, and I would like to use them as the input of COLMAP. I checked the guidance mentioned in the Readme.txt, and if you could share the script to transform the point track to the COLMAP feature format, it will help improve the usability. Thank you again.

**Comment by TanBinh93** [comment]
Hi,

Thank you for your interesting question.
I haven't worked on that project since last year.
The dense optical flow computation took a long time as you can see. We also
had a C++ version for this dense optical flow method developed by my former
colleague.

Now, my former team is working to improve the speed of optical flow
computation by rewriting the code in C++ and integrated it with GPU. The
new version will also be released in the near future. It is a full pipeline
for 3D reconstruction.

How to transform the point track to the COLMAP feature format is in the
link below:
https://colmap.github.io/tutorial.html#feature-detection-and-extraction
(see Feature Detection and Extraction part).
Next time, I will check the code and update the script to convert the point
track into COLMAP.

Thank you and best regards,
Binh

**Comment by TakiOrange** [comment]
Thank you for the quick reply!

Integrating it with GPU sounds quite interesting, and I believe it will make the computation much quicker. 
I'm looking forward to trying the new version in the near future. 

Thank you and your team again for the effort!

**Comment by TanBinh93** [comment]
You're welcome.
Thank you!
